services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
