version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    container_name: myfrontend
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - web

  nginx:
    build:
      context: ./nginx
    container_name: mynginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - web

networks:
  web:
    driver: bridge
