name: Frontend

on:
  pull_request:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run lint

  type-check:
    name: TypeScript
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run type-check

  cypress:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci

      - name: Run Vite + Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npx vite --host 0.0.0.0 --port 3000
          wait-on: http://127.0.0.1:3000
          wait-on-timeout: 90000
          command: npm run cypress:run
